### ISSUE TITLE
Traceback on running ./run.sh up -d

### ISSUE THREAD

**Issue by RainmakerRaw** [meyayl/docker-matrix-bootstrap#1]
I was pleased to find this project and hoped it would solve my running Matrix on my DS218+. Unfortunately, after changing the variables in `config` (domain, URLs, paths) and running `sudo ./run.sh prepare` followed by `sudo ./run.sh up -d` I encounter many errors: 

    ➜  docker-matrix-bootstrap git:(main) ✗ sudo ./run.sh prepare
    [ OK ] re-using host path for volume: /volume1/docker/matrix/synapse/data
    [ OK ] re-using host path for volume: /volume1/docker/matrix/db/data
    [ OK ] re-using host path for volume: /volume1/docker/matrix/element/config
    [ OK ] re-using existing homeserver.yaml (delete "/volume1/docker/matrix/synapse/data/homeserver.yaml" and "/volume1/docker/matrix/synapse/data/homeserver.yaml.bak" if you want a fresh start)
    [ OK ] rendering synapse homeserver.yaml
    [ OK ] rendering element config.json
    [ OK ] fixing permissions on /volume1/docker/matrix/synapse/data
    [ OK ] fixing permissions on /volume1/docker/matrix/db/data
    [ OK ] fixing permissions on /volume1/docker/matrix/element/config
    [ OK ] synapse: matching certificate found for matrix.oursecure.network, rending reverse proxy config
    [ OK ] element: matching certificate found for element.oursecure.network, rending reverse proxy config
    [ OK ] reloading nginx config to activate reverse proxy configuration
    
    ➜  docker-matrix-bootstrap git:(main) ✗ sudo ./run.sh up -d
    [ OK ] rendering docker-compose.yml and passing it to docker-compose
    Traceback (most recent call last):
      File "docker-compose", line 3, in <module>
      File "compose/cli/main.py", line 80, in main
      File "compose/cli/main.py", line 189, in perform_command
      File "compose/cli/command.py", line 70, in project_from_options
      File "compose/cli/command.py", line 144, in get_project
      File "compose/config/config.py", line 300, in find
      File "yaml/__init__.py", line 162, in safe_load
      File "yaml/__init__.py", line 114, in load
      File "yaml/constructor.py", line 49, in get_single_data
      File "yaml/composer.py", line 36, in get_single_node
      File "yaml/composer.py", line 55, in compose_document
      File "yaml/composer.py", line 84, in compose_node
      File "yaml/composer.py", line 133, in compose_mapping_node
      File "yaml/composer.py", line 84, in compose_node
      File "yaml/composer.py", line 133, in compose_mapping_node
      File "yaml/composer.py", line 84, in compose_node
      File "yaml/composer.py", line 133, in compose_mapping_node
      File "yaml/composer.py", line 84, in compose_node
      File "yaml/composer.py", line 127, in compose_mapping_node
      File "yaml/parser.py", line 98, in check_event
      File "yaml/parser.py", line 439, in parse_block_mapping_key
    yaml.parser.ParserError: while parsing a block mapping
      in "<stdin>", line 47, column 7
     expected <block end>, but found '<scalar>'
      in "<stdin>", line 49, column 45
    [10139] Failed to execute script docker-compose

Any ideas?

**Comment by meyayl** [comment]
Can you run `sudo ./run.sh write-compose` and share the rendered docker-compose.yml?
